project:
  type: website
  output-dir: ./docs

website:
  title: "Website"

  navbar:
    background: black
    pinned: true
    right:
      - text: "Slides"
        file: slides/presentation.html
      - icon: github
        href: https://github.com/vitay/quarto-website
        aria-label: GitHub

  sidebar:
    style: "docked"
    logo: img/tuc-new.png
    search: true
    contents:
      - text: "About"
        file: index.qmd
      - section: "Tutorial"
        contents:
        - src/Test.qmd

  page-footer:
    center: |
      Copyright 2024 - [Julien Vitay](mailto:julien.vitay@informatik.tu-chemnitz.de) - Chemnitz University of Technology

format:
  html:
    theme: [sandstone, "assets/webpage.scss"]
    page-layout: full
    smooth-scroll: true
    html-math-method: katex


bibliography: references.bib
csl: assets/frontiers.csl

highlight-style: github
code-line-numbers: false


