project:
  output-dir: ../../docs/slides

format:
  revealjs: 
    theme: [default, ../../slides.scss]
    slide-number: true
    html-math-method: katex
    chalkboard: 
      buttons: false

title-slide-attributes:
    data-background-image: "../img/tuc-new-large.png"
    data-background-size: 30%
    data-background-opacity: "1"
    data-background-position: top

bibliography: ../../references.bib
csl: ../../frontiers.csl

highlight-style: github
code-line-numbers: false

filters:
  - ../../center_images.lua
  - quarto