project:
  type: website
  output-dir: ../docs

website:
  title: "Website"

  navbar:
    background: black
    #logo: img/logowhite.png
    pinned: true
    right:
      - text: "Slides"
        file: slides/presentation.html
      - icon: github
        href: https://github.com/vitay/quarto-website
        aria-label: GitHub

  sidebar:
    style: "docked"
    logo: img/tuc-new.png
    search: true
    contents:
      - text: "About"
        file: index.qmd
      - section: "Tutorial"
        contents:
        - Test.qmd

  page-footer:
    center: |
      Copyright 2022 - Julien Vitay <julien.vitay@informatik.tu-chemnitz.de> - Chemnitz University of Technology

format:
  html:
    theme: [sandstone, ../webpage.scss]
    page-layout: full
    smooth-scroll: true
    html-math-method: katex

bibliography: ../references.bib
csl: ../frontiers.csl

highlight-style: github
code-line-numbers: false

filters:
  - ../center_images.lua
  - quarto

